# -*- coding: utf-8 -*-
"""Ajoute 5 QROC (qroc6..qroc10) aux cours FC09, FC15, FC22, FC23 pour atteindre 10/cours."""
import json, os

CONTENT = os.path.join(os.path.dirname(__file__), "..", "docs", "content", "qroc")

NEW = {
 "fc09": [
  {"id":"fc09-qroc6","difficulty":"facile","points":2,
   "question":"Distinguez les **antigènes tumoraux spécifiques (TSA)** des **antigènes tumoraux associés (TAA)**, et donnez un exemple de chacun.",
   "answer":"Les **TSA (Tumor-Specific Antigens)** sont **exclusivement exprimés par les cellules tumorales**, absents des cellules normales. Ils résultent de **mutations** (néo-antigènes) ou de protéines virales (ex : **E6/E7 du HPV** dans le cancer du col). Très immunogènes, ce sont des cibles idéales. Les **TAA (Tumor-Associated Antigens)** sont **présents aussi sur les cellules normales** mais **surexprimés** ou exprimés de façon aberrante par la tumeur : ex **HER2** (sein), antigènes de différenciation (**MART-1/Melan-A**, mélanome), antigènes onco-fœtaux (**ACE**, **AFP**). Moins spécifiques, ils exposent à un risque de réaction contre les tissus sains.",
   "keyPoints":["TSA : exclusifs à la tumeur (néo-antigènes mutés, HPV E6/E7)","TAA : présents sur cellules normales mais surexprimés (HER2, MART-1, ACE, AFP)","TSA = plus immunogènes et plus sûrs comme cibles"],
   "trap":"Les antigènes onco-fœtaux (ACE, AFP) sont des TAA (exprimés pendant la vie fœtale puis réprimés), pas des TSA."},
  {"id":"fc09-qroc7","difficulty":"moyen","points":3,
   "question":"Décrivez les grandes étapes du **cycle de l'immunité anti-tumorale** (cancer-immunity cycle), de la tumeur au ganglion puis le retour des LT effecteurs.",
   "answer":"Le cycle enchaîne : **(1)** libération d'**antigènes tumoraux** par les cellules cancéreuses (mort cellulaire) ; **(2)** **capture et apprêtement** par les **cellules dendritiques** ; **(3)** migration des DC vers le **ganglion** et **présentation** aux LT naïfs → **amorçage et activation** (avec costimulation) ; **(4)** **migration** des LT effecteurs par le sang vers la tumeur ; **(5)** **infiltration** du microenvironnement tumoral ; **(6)** **reconnaissance** des cellules tumorales via TCR/CMH-I ; **(7)** **destruction** (perforine/granzyme) → libération de nouveaux antigènes → ré-amplification du cycle. Chaque étape peut être bloquée par un mécanisme d'échappement et constitue une cible thérapeutique.",
   "keyPoints":["Libération d'Ag → capture par DC → présentation au ganglion → amorçage LT","Migration + infiltration des LT dans la tumeur","Reconnaissance (TCR-CMH-I) → destruction → ré-amplification","Chaque étape = cible thérapeutique potentielle"]},
  {"id":"fc09-qroc8","difficulty":"moyen","points":3,
   "question":"Les inhibiteurs de checkpoint exposent à des **effets indésirables immuno-médiés (irAE)**. Expliquez leur mécanisme, les principaux organes atteints et la prise en charge.",
   "answer":"En levant les freins physiologiques de l'activation lymphocytaire (CTLA-4, PD-1/PD-L1), ces médicaments provoquent une **activation auto-immune** non spécifique de la tumeur → **irAE (immune-related Adverse Events)**. Organes les plus touchés : **peau** (rash, prurit, vitiligo), **tube digestif** (colite, diarrhée), **endocrine** (thyroïdite, hypophysite, diabète), **foie** (hépatite), **poumon** (pneumopathie). Ces toxicités peuvent être **graves voire fatales** (grade 3-4). Prise en charge : **corticothérapie** (immunosuppression), parfois anti-TNF (**infliximab**) pour les colites résistantes, et **arrêt** temporaire ou définitif de l'immunothérapie selon la gravité. La combinaison anti-CTLA-4 + anti-PD-1 majore la fréquence des irAE.",
   "keyPoints":["Mécanisme : levée des freins → auto-immunité non ciblée","Organes : peau, digestif (colite), endocrine (thyroïde), foie, poumon","Grade 3-4 possible (grave)","PEC : corticoïdes ± anti-TNF, arrêt de l'immunothérapie"],
   "trap":"Un irAE n'est pas un signe d'inefficacité : la survenue de toxicité auto-immune est souvent corrélée à une meilleure réponse antitumorale."},
  {"id":"fc09-qroc9","difficulty":"difficile","points":4,
   "question":"Expliquez le principe des **CAR-T cells** : construction du récepteur, étapes de fabrication, principale indication et complication majeure.",
   "answer":"Les **CAR-T cells** (Chimeric Antigen Receptor T cells) sont des **LT du patient génétiquement modifiés** pour exprimer un **récepteur chimérique** combinant un domaine de reconnaissance extracellulaire (**scFv**, fragment d'anticorps anti-antigène tumoral, ex **anti-CD19**) et des domaines de signalisation intracellulaires (**CD3ζ** + costimulation **CD28** ou **4-1BB**). Étapes : **(1)** prélèvement des LT (leucaphérèse) ; **(2)** **transduction** du gène CAR (vecteur viral) ; **(3)** **expansion** in vitro ; **(4)** réinjection. Avantage : reconnaissance de l'antigène **indépendante du CMH** (contourne la perte de CMH-I). Indication principale : **hémopathies B** (LAL, lymphomes B réfractaires) via l'anti-CD19. Complication majeure : le **syndrome de relargage cytokinique (CRS)** — tempête de cytokines (**IL-6** ++) → fièvre, hypotension, défaillance multiviscérale, traité par **tocilizumab** (anti-IL-6R) ; également neurotoxicité (**ICANS**).",
   "keyPoints":["CAR = scFv (ex anti-CD19) + CD3ζ + costim (CD28/4-1BB)","Fabrication : leucaphérèse → transduction virale → expansion → réinjection","Reconnaissance indépendante du CMH","Indication : hémopathies B (LAL, lymphome B)","Complication : CRS (IL-6) → tocilizumab ; neurotoxicité ICANS"],
   "trap":"Les CAR-T reconnaissent l'antigène sans présentation par le CMH : c'est leur force contre les tumeurs ayant perdu le CMH-I. La cible anti-CD19 explique l'aplasie B et l'hypogammaglobulinémie."},
  {"id":"fc09-qroc10","difficulty":"moyen","points":3,
   "question":"Que distingue une tumeur **« chaude »** d'une tumeur **« froide »** sur le plan immunologique, et quelle est la valeur pronostique des **TILs** ?",
   "answer":"Une tumeur **« chaude » (inflammée)** est **infiltrée par des lymphocytes T** (notamment CD8 cytotoxiques) : les **TILs (Tumor-Infiltrating Lymphocytes)**. Elle répond généralement **mieux à l'immunothérapie** (inhibiteurs de checkpoint) et est de **meilleur pronostic**. Une tumeur **« froide » (non infiltrée)** est **dépourvue d'infiltrat lymphocytaire** (exclusion ou désert immunitaire) → **mauvaise réponse** aux checkpoints et **moins bon pronostic**. La **densité et la localisation des TILs** (concept d'**Immunoscore**) ont une valeur pronostique forte, parfois supérieure à la classification TNM (ex : cancer du côlon). Des stratégies visent à « réchauffer » les tumeurs froides (vaccins, virus oncolytiques, combinaisons).",
   "keyPoints":["Chaude = infiltrée de LT CD8 (TILs) → bonne réponse aux checkpoints, bon pronostic","Froide = pas d'infiltrat → mauvaise réponse, mauvais pronostic","TILs/Immunoscore : valeur pronostique forte (parfois > TNM)","Objectif : « réchauffer » les tumeurs froides"]},
 ],
 "fc15": [
  {"id":"fc15-qroc6","difficulty":"moyen","points":3,
   "question":"Quel est le rôle du **système HLA** dans la transplantation ? Précisez les locus les plus importants à apparier et la conséquence d'une incompatibilité.",
   "answer":"Le **système HLA** (CMH humain, sur le **chromosome 6**) code les molécules de présentation antigénique qui constituent les principaux **allo-antigènes** reconnus lors du rejet. En transplantation d'organe, on **apparie** donneur et receveur sur les locus **HLA-A, -B (classe I)** et surtout **HLA-DR (classe II)**, les plus immunogènes. Plus le nombre d'**incompatibilités (mismatches)** est élevé, plus le risque de rejet et d'immunisation (apparition d'Ac anti-HLA) augmente, et plus la survie du greffon diminue. Le système HLA étant très **polymorphe**, un appariement parfait est rare hors fratrie HLA-identique. L'appariement est crucial en greffe de **moelle osseuse** (risque de GVH), un peu moins en greffe rénale où l'immunosuppression compense en partie.",
   "keyPoints":["HLA = CMH (chromosome 6) = principaux allo-antigènes du rejet","Apparier surtout HLA-A, -B (classe I) et HLA-DR (classe II)","Plus de mismatches → plus de rejet/immunisation, moins de survie","Appariement crucial en greffe de moelle (GVH)"]},
  {"id":"fc15-qroc7","difficulty":"difficile","points":4,
   "question":"Qu'est-ce que la **réaction du greffon contre l'hôte (GVHD)** ? Contexte de survenue, mécanisme et organes atteints ?",
   "answer":"La **GVHD (Graft-versus-Host Disease)** est la situation **inverse du rejet** : ce sont les **cellules immunocompétentes du greffon** (LT du donneur) qui attaquent les **tissus du receveur**. Elle survient typiquement après une **allogreffe de cellules souches hématopoïétiques (moelle osseuse)**, où le greffon contient des LT matures du donneur, chez un receveur immunodéprimé incapable de les rejeter. Mécanisme : les LT du donneur reconnaissent les **allo-antigènes HLA (et mineurs) du receveur** comme étrangers → activation et attaque. Organes cibles : **peau** (érythème, rash), **foie** (cholestase, ictère), **tube digestif** (diarrhée). On distingue formes **aiguë** et **chronique**. Prévention : immunosuppression (ciclosporine, méthotrexate), déplétion T du greffon. À l'inverse, l'effet **GVL (greffon contre leucémie)** est bénéfique dans les hémopathies.",
   "keyPoints":["GVHD = LT du donneur attaquent les tissus du receveur (inverse du rejet)","Contexte : allogreffe de CSH (moelle), receveur immunodéprimé","Organes : peau, foie, tube digestif","Prévention : immunosuppression, déplétion T ; effet GVL bénéfique"],
   "trap":"La GVHD nécessite un greffon contenant des cellules immunocompétentes (moelle) et un receveur incapable de les rejeter. Ne pas confondre avec le rejet (hôte contre greffon)."},
  {"id":"fc15-qroc8","difficulty":"moyen","points":3,
   "question":"Décrivez la **stratégie immunosuppressive** classique en transplantation d'organe : phases et principe d'association des molécules.",
   "answer":"Deux phases : **(1) Traitement d'induction** : immunosuppression **intense** au moment de la greffe et juste après, période à plus haut risque de rejet aigu (ex : anti-récepteur de l'IL-2 / **basiliximab**, ou sérum anti-lymphocytaire / **thymoglobulines**). **(2) Traitement d'entretien** : immunosuppression au long cours, à doses **progressivement réduites**, poursuivie **à vie**. Principe central : **associer des molécules aux mécanismes d'action différents** (souvent une **trithérapie** : inhibiteur de calcineurine + antimétabolite + corticoïdes) pour agir sur plusieurs étapes de l'activation lymphocytaire, ce qui permet de **réduire les doses** de chacune (et leur toxicité) tout en maximisant l'efficacité. Objectif : prévenir le rejet sans immunodépression excessive (infections, cancers).",
   "keyPoints":["Induction : immunosuppression forte péri-greffe (basiliximab, thymoglobulines)","Entretien : doses réduites, à vie","Trithérapie : anticalcineurine + antimétabolite + corticoïdes (mécanismes différents)","Associer des mécanismes différents → ↓ doses et toxicité"]},
  {"id":"fc15-qroc9","difficulty":"moyen","points":3,
   "question":"Qu'est-ce qu'un **site immunoprivilégié** ? Donnez des exemples et expliquez l'intérêt en transplantation (ex : greffe de cornée).",
   "answer":"Un **site immunoprivilégié** est un tissu où une **réponse immunitaire est physiologiquement limitée**, permettant de tolérer des antigènes étrangers sans rejet majeur. Mécanismes : **barrières anatomiques** (absence de drainage lymphatique direct, jonctions serrées), **faible expression du CMH**, environnement **immunosuppresseur local** (TGF-β, expression de **FasL** induisant l'apoptose des LT infiltrants). Exemples : **œil (chambre antérieure, cornée)**, **cerveau/SNC**, **testicule**, **placenta/fœtus**. Intérêt : la **greffe de cornée** est l'allogreffe la **plus pratiquée** et réussit **sans immunosuppression systémique ni typage HLA** dans la majorité des cas, grâce au privilège immunitaire de l'œil (avascularité de la cornée).",
   "keyPoints":["Site où la réponse immune est physiologiquement limitée","Mécanismes : pas de drainage lymphatique, faible CMH, FasL/TGF-β","Exemples : œil/cornée, SNC, testicule, placenta","Greffe de cornée : sans immunosuppression systémique ni typage HLA"]},
  {"id":"fc15-qroc10","difficulty":"moyen","points":3,
   "question":"Quelles sont les principales **complications de l'immunosuppression au long cours** chez le transplanté ?",
   "answer":"L'immunosuppression à vie expose à des complications liées à la **baisse des défenses** et à la **toxicité** des molécules : **(1) Infections** — surtout **opportunistes** (**CMV**, **BK virus**, pneumocystose, candidoses, tuberculose) et infections communautaires plus sévères ; les **vaccins vivants atténués sont contre-indiqués**. **(2) Cancers** — risque accru de **lymphomes** (souvent EBV-induits : syndrome lymphoprolifératif post-transplantation, **PTLD**), **cancers cutanés** et cancers viro-induits. **(3) Toxicités spécifiques** — néphrotoxicité des anticalcineurines, diabète, HTA, dyslipidémie, ostéoporose (corticoïdes), toxicité médullaire (antimétabolites). D'où une surveillance régulière (taux résiduels, NFS, créatinine, dépistage cutané).",
   "keyPoints":["Infections opportunistes (CMV, BK, pneumocystose) ; vaccins vivants CI","Cancers : lymphomes EBV (PTLD), cancers cutanés","Toxicités : néphrotoxicité (anticalcineurines), diabète, HTA, ostéoporose","Surveillance régulière (taux, NFS, créatinine, peau)"]},
 ],
 "fc22": [
  {"id":"fc22-qroc6","difficulty":"moyen","points":3,
   "question":"Expliquez le **privilège immunitaire** du système nerveux central : rôle de la **barrière hémato-encéphalique** et conséquences en pathologie.",
   "answer":"Le **SNC** est un **site immunoprivilégié** : en conditions physiologiques, il est **dépourvu de cellules immunitaires périphériques**, seule la **microglie** (macrophages résidents) y assure l'immunité innée. Le privilège repose sur : la **barrière hémato-encéphalique (BHE)** — jonctions serrées entre cellules endothéliales limitant le passage des cellules et molécules immunitaires ; l'**absence de drainage lymphatique** conventionnel ; une **faible expression du CMH** par les cellules neurales. Conséquence : lorsque la BHE est **perméabilisée** (inflammation), des lymphocytes T auto-réactifs et des anticorps peuvent **infiltrer** le SNC et déclencher des maladies neuro-immunes (ex : **SEP**). À l'inverse, la présence de cellules immunitaires périphériques dans le tissu cérébral **témoigne toujours d'une pathologie**.",
   "keyPoints":["SNC immunoprivilégié : pas de cellules immunes périphériques en temps normal","BHE (jonctions serrées) + pas de drainage lymphatique + faible CMH","Microglie = seule immunité résidente","Perméabilisation BHE → infiltration → maladies neuro-immunes (SEP)"]},
  {"id":"fc22-qroc7","difficulty":"moyen","points":3,
   "question":"Décrivez les principales **formes évolutives de la sclérose en plaques** et le principe des **traitements de fond**.",
   "answer":"La **SEP** évolue selon plusieurs formes : **(1) Rémittente-récurrente (poussées-rémissions)** — la plus fréquente au début (~85 %) : épisodes neurologiques (poussées) suivis de récupération partielle ou complète. **(2) Secondairement progressive** : après des années, aggravation progressive et continue du handicap. **(3) Primaire progressive** : aggravation d'emblée, sans poussées nettes (~15 %). Les **traitements de fond** (immunomodulateurs/immunosuppresseurs) réduisent la fréquence des poussées et ralentissent la progression : **interféron β**, acétate de glatiramère, biothérapies (**anti-CD20 / ocrélizumab**, **natalizumab** anti-intégrine α4 bloquant le passage des LT à travers la BHE, fingolimod…). Les **poussées aiguës** sont traitées par **corticothérapie** à forte dose (bolus de méthylprednisolone).",
   "keyPoints":["Rémittente-récurrente (~85 % au début) : poussées + rémissions","Secondairement progressive : aggravation après phase rémittente","Primaire progressive (~15 %) : progressive d'emblée","Fond : IFN-β, anti-CD20 (ocrélizumab), natalizumab ; poussée : corticoïdes IV"]},
  {"id":"fc22-qroc8","difficulty":"difficile","points":4,
   "question":"Qu'est-ce que la **neuromyélite optique (maladie de Devic)** ? Précisez la cible antigénique et ce qui la distingue de la SEP.",
   "answer":"La **neuromyélite optique (NMO)** ou **maladie de Devic** est une maladie auto-immune **démyélinisante du SNC** caractérisée par l'atteinte préférentielle du **nerf optique (névrite optique)** et de la **moelle épinière (myélite extensive)**. Sa particularité : des **auto-anticorps dirigés contre l'aquaporine-4 (anti-AQP4)**, un **canal hydrique** exprimé par les **astrocytes** (pieds astrocytaires au contact de la BHE). Ces Ac sont **directement pathogènes** (activation du complément → astrocytopathie). Distinction avec la SEP : la cible est l'**astrocyte (AQP4)** et non l'oligodendrocyte/myéline ; les Ac anti-AQP4 sont spécifiques ; l'atteinte est plus sévère et le traitement diffère (les traitements de la SEP comme l'IFN-β peuvent **aggraver** la NMO). Traitement : corticoïdes, échanges plasmatiques, **rituximab (anti-CD20)**, anti-complément (eculizumab).",
   "keyPoints":["NMO/Devic : névrite optique + myélite, démyélinisation du SNC","Cible : aquaporine-4 (AQP4) des astrocytes (anti-AQP4 pathogènes, complément)","Distinction SEP : astrocyte (≠ oligodendrocyte), Ac spécifiques anti-AQP4","Traitement : rituximab, échanges plasmatiques (IFN-β aggrave la NMO)"],
   "trap":"Donner un traitement de fond de SEP (interféron β) à une NMO peut aggraver la maladie : d'où l'importance du dosage des anti-AQP4 pour les distinguer."},
  {"id":"fc22-qroc9","difficulty":"difficile","points":4,
   "question":"Définissez les **syndromes neurologiques paranéoplasiques** et expliquez leur mécanisme immunologique (anticorps onconeuronaux).",
   "answer":"Les **syndromes neurologiques paranéoplasiques** sont des atteintes neurologiques **à distance d'un cancer**, **non liées** à un envahissement direct, à des métastases ou à un effet toxique, mais d'origine **immunologique**. Mécanisme : la tumeur exprime des **antigènes normalement neuronaux (antigènes onconeuronaux)** ; la réponse anti-tumorale **réagit de façon croisée** avec le tissu nerveux → production d'**anticorps onconeuronaux** et de LT auto-réactifs attaquant le SNC ou le SNP. Exemples : **anti-Hu** (cancer pulmonaire à petites cellules → encéphalomyélite, neuropathie), **anti-Yo** (cancer ovaire/sein → dégénérescence cérébelleuse), anti-CV2/CRMP5. Ces syndromes peuvent **précéder** la découverte du cancer → leur détection impose une **recherche de néoplasie**. Traitement : celui du cancer + immunomodulation.",
   "keyPoints":["Atteinte neuro à distance d'un cancer, d'origine immunitaire (pas d'invasion directe)","Antigènes onconeuronaux : réaction croisée tumeur ↔ tissu nerveux","Ac : anti-Hu (CPPC), anti-Yo (ovaire/sein → cervelet)","Peut précéder le cancer → rechercher une néoplasie"]},
  {"id":"fc22-qroc10","difficulty":"moyen","points":3,
   "question":"Quel est le rôle des sous-populations lymphocytaires **Th17** et **Treg** dans les maladies neuro-inflammatoires comme la SEP ?",
   "answer":"L'équilibre entre lymphocytes **effecteurs** et **régulateurs** est déterminant. Les **LT Th17** (produisant l'**IL-17**) et les **Th1** (IFN-γ) sont **pro-inflammatoires** : ils franchissent la BHE, recrutent d'autres cellules immunitaires et participent à la **démyélinisation** (rôle central démontré dans le modèle expérimental d'encéphalomyélite auto-immune, **EAE**). À l'inverse, les **LT régulateurs (Treg)** sont **protecteurs** : ils freinent la réponse auto-immune et favorisent la tolérance. Dans la SEP, on observe un **déséquilibre** en faveur des effecteurs (Th17/Th1) avec un **déficit fonctionnel des Treg**, entretenant l'attaque de la myéline. (Note : la grossesse, en favorisant un profil Th2/Treg, réduit transitoirement les poussées de SEP.)",
   "keyPoints":["Th17 (IL-17) et Th1 (IFN-γ) : pro-inflammatoires, démyélinisation (modèle EAE)","Treg : protecteurs, tolérance","SEP : déséquilibre effecteurs > Treg","Grossesse (profil Th2/Treg) → ↓ poussées"]},
 ],
 "fc23": [
  {"id":"fc23-qroc6","difficulty":"moyen","points":3,
   "question":"Qu'est-ce que le **syndrome de fatigue chronique** (encéphalomyélite myalgique) et quel lien entretient-il avec certaines infections virales ?",
   "answer":"Le **syndrome de fatigue chronique (SFC)**, ou **encéphalomyélite myalgique (EM/SFC)**, est un syndrome post-infectieux caractérisé par une **fatigue intense, persistante (> 6 mois) et invalidante**, non soulagée par le repos, aggravée par l'effort (**malaise post-effort**), associée à des troubles du sommeil, des douleurs et des troubles neurocognitifs (« brouillard cérébral »). Il survient fréquemment **au décours d'une infection virale**, notamment par le **virus d'Epstein-Barr (EBV)** (après une mononucléose infectieuse), mais aussi d'autres agents. Les mécanismes évoqués rejoignent ceux des autres syndromes post-infectieux : **dysrégulation immunitaire**, inflammation persistante, **réactivation virale** et dysautonomie. Le diagnostic est **clinique et d'exclusion** ; pas de traitement spécifique (prise en charge symptomatique, gestion de l'effort).",
   "keyPoints":["SFC/EM : fatigue invalidante > 6 mois, malaise post-effort, troubles cognitifs","Survient au décours d'infections virales (EBV ++ après MNI)","Mécanismes : dysrégulation immunitaire, inflammation, réactivation virale","Diagnostic clinique d'exclusion, pas de traitement spécifique"]},
  {"id":"fc23-qroc7","difficulty":"moyen","points":3,
   "question":"Décrivez le **syndrome post-maladie de Lyme** (PTLDS) : définition, symptômes et mécanismes évoqués.",
   "answer":"Le **syndrome post-traitement de la maladie de Lyme (PTLDS)** désigne la **persistance de symptômes** après un traitement antibiotique **bien conduit** d'une borréliose de Lyme (infection à **Borrelia burgdorferi**, transmise par les tiques). Symptômes persistant des mois : **fatigue**, **douleurs musculo-articulaires (arthralgies)**, **troubles neurocognitifs**, parfois troubles de l'humeur. Mécanismes proposés (communs aux syndromes post-infectieux) : **réaction auto-immune** post-infectieuse (mimétisme moléculaire), **inflammation résiduelle**, persistance d'antigènes bactériens, séquelles tissulaires. Une **antibiothérapie prolongée n'a pas démontré d'efficacité** (l'infection active étant éradiquée) ; la prise en charge est symptomatique. Le diagnostic d'exclusion impose d'éliminer une réinfection ou une autre cause.",
   "keyPoints":["PTLDS : symptômes persistants après traitement ATB efficace de Lyme (Borrelia)","Fatigue, arthralgies, troubles neurocognitifs","Mécanismes : auto-immunité (mimétisme), inflammation résiduelle","Antibiothérapie prolongée inefficace → PEC symptomatique"]},
  {"id":"fc23-qroc8","difficulty":"moyen","points":3,
   "question":"Expliquez le concept de **mimétisme moléculaire** comme mécanisme d'auto-immunité post-infectieuse et donnez deux exemples de maladies.",
   "answer":"Le **mimétisme moléculaire** est un mécanisme par lequel une **infection déclenche une auto-immunité** : certains **antigènes du pathogène ressemblent structurellement à des antigènes du soi**. La réponse dirigée contre l'agent infectieux **réagit de façon croisée** avec les tissus de l'hôte (LT et/ou anticorps), provoquant des lésions auto-immunes une fois l'infection résolue. Exemples : **(1)** le **syndrome de Guillain-Barré** après infection à *Campylobacter jejuni* (Ac croisant avec les **gangliosides de la myéline du SNP**) ; **(2)** le **rhumatisme articulaire aigu** après angine à **streptocoque β-hémolytique du groupe A** (Ac croisant avec le cœur, les articulations, le SNC). Ce mécanisme explique le **délai** entre l'infection et l'apparition des symptômes auto-immuns.",
   "keyPoints":["Mimétisme : antigène du pathogène ≈ antigène du soi → réaction croisée","Guillain-Barré post-Campylobacter (gangliosides myéline SNP)","Rhumatisme articulaire aigu post-streptocoque A (cœur, articulations)","Explique le délai infection → auto-immunité"]},
  {"id":"fc23-qroc9","difficulty":"moyen","points":3,
   "question":"Quels sont les **principes de prise en charge** des syndromes post-infectieux (type COVID long) et pourquoi le diagnostic est-il difficile ?",
   "answer":"Le diagnostic est **difficile** car les symptômes sont **multiples, fluctuants et non spécifiques** (fatigue, douleurs, troubles cognitifs), il n'existe **pas de marqueur biologique spécifique**, et c'est un **diagnostic d'exclusion** (éliminer toute autre cause). La prise en charge est essentiellement **symptomatique et multidisciplinaire** : **réadaptation adaptée** (réentraînement progressif à l'effort en évitant le malaise post-effort), prise en charge de la **douleur**, du **sommeil**, **soutien psychologique**, traitement des comorbidités. Il n'existe pas (à ce jour) de **traitement curatif** ciblant le mécanisme. La **prévention** repose sur la **vaccination** (qui réduit le risque de COVID long) et la prévention des infections. La reconnaissance de ces syndromes est importante pour la **prise en charge sociale** des patients.",
   "keyPoints":["Diagnostic difficile : symptômes non spécifiques, pas de marqueur, exclusion","PEC symptomatique multidisciplinaire : réadaptation à l'effort, douleur, sommeil, psy","Pas de traitement curatif spécifique","Prévention : vaccination ; enjeu social fort"]},
  {"id":"fc23-qroc10","difficulty":"difficile","points":4,
   "question":"Opposez les deux grands mécanismes des symptômes post-infectieux prolongés : **persistance de l'agent/antigène** et **dérèglement immunitaire auto-entretenu**. Quelles implications thérapeutiques ?",
   "answer":"Deux familles de mécanismes, **non exclusives**. **(1) Persistance de l'agent ou de ses antigènes** : du **matériel viral** (ARN, protéines) ou bactérien persiste dans des **réservoirs tissulaires** (intestin, ganglions, SNC…) après la phase aiguë, entretenant une **stimulation immunitaire chronique** et une inflammation locale (démontré pour le SARS-CoV-2, évoqué pour le Chikungunya via les macrophages). Implication : des stratégies **antivirales/anti-pathogènes** pourraient théoriquement être utiles si la persistance est confirmée. **(2) Dérèglement immunitaire auto-entretenu** : même après élimination de l'agent, le SI reste **anormalement activé** — **auto-anticorps** (mimétisme), **réactivation de virus latents (EBV)**, inflammation chronique, dysrégulation cytokinique. Implication : approches **immunomodulatrices**. En pratique, la coexistence probable des deux mécanismes explique l'absence de traitement univoque et la nécessité de **phénotyper** les patients.",
   "keyPoints":["Persistance : antigènes viraux/bactériens dans des réservoirs → stimulation chronique","Dérèglement immunitaire : auto-Ac, réactivation EBV, inflammation auto-entretenue","Implications : antiviraux (si persistance) vs immunomodulation (si dysimmunité)","Mécanismes non exclusifs → phénotypage nécessaire, pas de traitement univoque"]},
 ],
}

for slug, extra in NEW.items():
    path = os.path.join(CONTENT, slug + ".json")
    with open(path, encoding="utf-8") as f:
        d = json.load(f)
    existing_ids = {q["id"] for q in d["questions"]}
    added = 0
    for q in extra:
        if q["id"] in existing_ids:
            continue
        d["questions"].append(q)
        added += 1
    with open(path, "w", encoding="utf-8") as f:
        f.write(json.dumps(d, indent=1, ensure_ascii=False) + "\n")
    print(f"{slug}: +{added} -> {len(d['questions'])} questions")
